extends:
  - airbnb-typescript
  - plugin:import/typescript
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
env:
  browser: true
  node: true
  es6: true
  jest: true
plugins:
  - import
  - react
  - react-hooks
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/explicit-module-boundary-types": 0
  react/prop-types: 0
  import/extentions: 0
  react/jsx-props-no-spreading: 0
  "@typescript-eslint/ban-ts-comment": 0
