extends:
  - airbnb-typescript
  - plugin:import/typescript
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
env:
  browser: true
  node: true
  es6: true
  jest: true
plugins:
  - import
  - react
  - react-hooks
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-non-null-assertion": 0
